### ISSUE TITLE
gcloud_init() fails to find python executable on Windows

### ISSUE THREAD

**Issue by andrie** [rstudio/cloudml#123]
I'm running Windows 10 with `cloudml_0.5`. My installation of python comes from *Anaconda*.

When I try to switch CloudML users with `gcloud_init()`, I get terminal errors.  It seems that the RStudio terminal can't find the correct python binaries.

However, if I run `gcloud init` in Windows Powershell, everything works fine.

```r
cloudml::gcloud_init()
```

In the terminal I get:

```
$ gcloud init
which: no python2 in (/c/Rtools/bin:/c/Program Files/R/R-3.4.3/bin/x64:
/c/tools/Anaconda3/Scripts:/c/tools/Anaconda3:/c/Program Files/Docker/D
ocker/Resources/bin:/c/tools/Anaconda3/envs/r-tensorflow/Library/bin:/c
/Program Files/R/R-3.4.2/bin/x64:/c/Rtools/bin:/c/Rtools/mingw_64/bin:/
c/Rtools/mingw_32/bin:/c/Python36/Scripts:/c/Python36:/c/WINDOWS/system
32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPower
Shell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/vim/vim
80:/c/Program Files/TortoiseGit/bin:/c/Program Files/MiKTeX 2.9/miktex/
bin/x64:/c/Program Files/qpdf/bin:/c/Program Files/PuTTY:/cmd:/c/Users/
apdev/AppData/Local/Microsoft/WindowsApps:/c/Program Files/Microsoft VS
 Code/bin:/c/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sd
k/bin:/bin:/c/Users/apdev:/c/Program Files/RStudio/bin/msys-ssh-1000-18
)
which: no python2.7 in (/c/Rtools/bin:/c/Program Files/R/R-3.4.3/bin/x6
4:/c/tools/Anaconda3/Scripts:/c/tools/Anaconda3:/c/Program Files/Docker
/Docker/Resources/bin:/c/tools/Anaconda3/envs/r-tensorflow/Library/bin:
/c/Program Files/R/R-3.4.2/bin/x64:/c/Rtools/bin:/c/Rtools/mingw_64/bin
:/c/Rtools/mingw_32/bin:/c/Python36/Scripts:/c/Python36:/c/WINDOWS/syst
em32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPow
erShell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/vim/v
im80:/c/Program Files/TortoiseGit/bin:/c/Program Files/MiKTeX 2.9/mikte
x/bin/x64:/c/Program Files/qpdf/bin:/c/Program Files/PuTTY:/cmd:/c/User
s/apdev/AppData/Local/Microsoft/WindowsApps:/c/Program Files/Microsoft
VS Code/bin:/c/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-
sdk/bin:/bin:/c/Users/apdev:/c/Program Files/RStudio/bin/msys-ssh-1000-
18)
Traceback (most recent call last):
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/
lib/gcloud.py", line 60, in main
    gcloud_main = _import_gcloud_main()
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/
lib/gcloud.py", line 43, in _import_gcloud_main
    import googlecloudsdk.gcloud_main
  File "C:\Users\apdev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\
lib\googlecloudsdk\gcloud_main.py", line 28, in <module>
    from googlecloudsdk.calliope import base
  File "C:\Users\apdev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\
lib\googlecloudsdk\calliope\base.py", line 22, in <module>
    import re
  File "C:\tools\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/
lib/gcloud.py", line 88, in <module>
    main()
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/
lib/gcloud.py", line 64, in main
    import traceback
  File "C:\tools\Anaconda3\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\tools\Anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\tools\Anaconda3\lib\tokenize.py", line 33, in <module>
    import re
  File "C:\tools\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by jjallaire** [comment]
This might be crosstalk between Python 3 and Python 2 installations. See https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag/45716067

Is there a PYTHONPATH environment variable defined somehwere?

@javierluraschi I am OOF this week could you try to narrow this down with @andrie ?

I just put tfruns on CRAN so once we work through these issues I think we will be ready for a cloudml CRAN release.

**Comment by javierluraschi** [comment]
We think we have a repro which to use `cloudml` with python installed through conda, planning to try to reproduce this sometime this week and push a fix or get back to Andrie to get more info on this. Thanks for the pointers, JJ.

**Comment by javierluraschi** [comment]
Alright, thanks @andrie , found a repro here, which is unrelated to Anaconda and specific to Windows.

The Google installer adds gcloud to the PATH but restarting the rsession does not read the PATH changes until RStudio is restarted, fix should be to use the full path rather than relying on the PATH.

**Comment by andrie** [comment]
Ahah. This explains why I couldn't reproduce in exactly the same way after restarting my machine to demo this to you!
