### ISSUE TITLE
Updating gcloud SDK components from terminal throws error on Windows

### ISSUE THREAD

**Issue by andrie** [rstudio/cloudml#152]
During a training run the service responded with this message:

```
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update
```

So I tried this in the RStudio terminal, and received an error:

```
$ gcloud components update
which: no python2 in (/c/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd:/c/R/R
-3.4.4/bin/x64:/c/Program Files/Docker/Docker/Resources/bin:/c/Program Files/R/R-3.4.2/bin/x64:/c/Rtools/b
in:/c/Users/apdev/AppData/Local/Pandoc:/c/ProgramData/Oracle/Java/javapath:/c/tools/Anaconda3/Scripts:/c/t
ools/Anaconda3:/c/tools/Anaconda3/envs/r-tensorflow/Library/bin:/c/Rtools/mingw_64/bin:/c/Rtools/mingw_32/
bin:/c/Python36/Scripts:/c/Python36:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/Sys
tem32/WindowsPowerShell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/vim/vim80:/c/Program Fil
es/MiKTeX 2.9/miktex/bin/x64:/c/Program Files/qpdf/bin:/c/Program Files/PuTTY:/cmd:/c/Program Files/Tortoi
seGit/bin:/c/Program Files/Amazon/AWSCLI:/c/WINDOWS/System32/OpenSSH:/c/Users/apdev/AppData/Local/Microsof
t/WindowsApps:/c/Program Files/Microsoft VS Code/bin:/c/Users/apdev/AppData/Local/Google/Cloud SDK/google-
cloud-sdk/bin:/c/Users/apdev/AppData/Local/Pandoc:/bin:/c/Users/apdev:/c/Program Files/RStudio/bin/msys-ss
h-1000-18)
which: no python2.7 in (/c/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd:/c/R
/R-3.4.4/bin/x64:/c/Program Files/Docker/Docker/Resources/bin:/c/Program Files/R/R-3.4.2/bin/x64:/c/Rtools
/bin:/c/Users/apdev/AppData/Local/Pandoc:/c/ProgramData/Oracle/Java/javapath:/c/tools/Anaconda3/Scripts:/c
/tools/Anaconda3:/c/tools/Anaconda3/envs/r-tensorflow/Library/bin:/c/Rtools/mingw_64/bin:/c/Rtools/mingw_3
2/bin:/c/Python36/Scripts:/c/Python36:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/S
ystem32/WindowsPowerShell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/vim/vim80:/c/Program F
iles/MiKTeX 2.9/miktex/bin/x64:/c/Program Files/qpdf/bin:/c/Program Files/PuTTY:/cmd:/c/Program Files/Tort
oiseGit/bin:/c/Program Files/Amazon/AWSCLI:/c/WINDOWS/System32/OpenSSH:/c/Users/apdev/AppData/Local/Micros
oft/WindowsApps:/c/Program Files/Microsoft VS Code/bin:/c/Users/apdev/AppData/Local/Google/Cloud SDK/googl
e-cloud-sdk/bin:/c/Users/apdev/AppData/Local/Pandoc:/bin:/c/Users/apdev:/c/Program Files/RStudio/bin/msys-
ssh-1000-18)
Traceback (most recent call last):
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/lib/gcloud.py", line 60, in main
    gcloud_main = _import_gcloud_main()
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/lib/gcloud.py", line 43, in _import
_gcloud_main
    import googlecloudsdk.gcloud_main
  File "C:\Users\apdev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\gcloud_main.py",
 line 28, in <module>
    from googlecloudsdk.calliope import base
  File "C:\Users\apdev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\base.py
", line 22, in <module>
    import re
  File "C:\tools\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/lib/gcloud.py", line 88, in <module
>
    main()
  File "C:/Users/apdev/AppData/Local/Google/Cloud SDK/google-cloud-sdk/lib/gcloud.py", line 64, in main
    import traceback
  File "C:\tools\Anaconda3\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\tools\Anaconda3\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\tools\Anaconda3\lib\tokenize.py", line 33, in <module>
    import re
  File "C:\tools\Anaconda3\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

Here is my session info:

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-05-24                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       source                          
 assertthat    0.2.0   2017-04-11 CRAN (R 3.4.0)                  
 backports     1.1.2   2017-12-13 CRAN (R 3.4.3)                  
 base64enc     0.1-3   2015-07-28 CRAN (R 3.4.0)                  
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.2)                  
 cloudml     * 0.5     2018-05-23 Github (rstudio/cloudml@4ce808c)
 crayon        1.3.4   2017-09-16 CRAN (R 3.4.2)                  
 debugme       1.1.0   2017-10-22 CRAN (R 3.4.2)                  
 jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)                  
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)                  
 packrat       0.4.9-2 2018-04-20 CRAN (R 3.4.4)                  
 processx      3.1.0   2018-05-15 CRAN (R 3.4.4)                  
 R6            2.2.2   2017-06-17 CRAN (R 3.4.1)                  
 rprojroot     1.3-2   2018-01-03 CRAN (R 3.4.3)                  
 rstudioapi    0.7     2017-09-07 CRAN (R 3.4.1)                  
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.3)                  
 tfruns      * 1.3     2018-04-10 Github (rstudio/tfruns@282de31) 
 whisker       0.3-2   2013-04-28 CRAN (R 3.4.0)                  
 withr         2.1.2   2018-03-15 CRAN (R 3.4.4)                  
 yaml          2.1.19  2018-05-01 CRAN (R 3.4.4)    
```

**Comment by javierluraschi** [comment]
I can reproduce this one with the `git bash` terminal, @andrie, have you tried the `command prompt` option from RStudio?

<img width="706" alt="screen shot 2018-05-31 at 2 01 36 pm" src="https://user-images.githubusercontent.com/3478847/40808212-486a152c-64db-11e8-822f-2cac7b60b98a.png">

<img width="588" alt="screen shot 2018-05-31 at 2 01 50 pm" src="https://user-images.githubusercontent.com/3478847/40808219-4c8b74de-64db-11e8-9cb6-290389e751e9.png">

**Comment by javierluraschi** [comment]
Added warning to help users switch to `Command Prompt` in Windows for async job collection, planning to explicitly open this prompt once this feature becomes available.

**Comment by andrie** [comment]
Good catch, @javierluraschi 

I can confirm that I previously used the default terminal (git bash), but when changing my global options to some of the other terminal this actually works.

I've successfully tried the Windows 64-bit terminal.

I will also try the Powershell terminal and the LSW bash terminal and report back.

**Comment by javierluraschi** [comment]
PowerShell is broken, Gary seems interested in implementing https://github.com/rstudio/rstudio/issues/2903, once we have that, we can force using the command prompt, for now we are left only with a warning.
